### ISSUE TITLE
Big images are really broken

### ISSUE THREAD

**Issue by CallMeEchoCodes** [mekb-turtle/Foto#15]
### Bug description
Big images cause a lot of lag and open absolutely massive windows. I tested on a 3264x2448 image. It causes delay when resizing and a window bigger than the monitor.
I would fix the massive window by limiting the window size to something (half the monitor size?) and allowing users to resize above that. idk about the lag tho.

### Steps to reproduce
1. Open a big image
2. Make it float
3. Resize the window

### Progress Tracker
- [ ] Fix lag
- [ ] Fix massive window

**Comment by mekb-turtle** [comment]
Fixed in the rewrite
